/** Phaser texture keys loaded from public/game/sprites/*.png */
export const SHEET_TEXTURE_KEYS = [
  'mario_s_idle',
  'mario_small_walk1',
  'mario_small_walk2',
  'mario_small_jump',
  'mario_s_die',
  'mario_b_idle',
  'mario_big_walk1',
  'mario_big_walk2',
  'mario_big_walk3',
  'mario_big_jump',
  'mario_f_idle',
  'mario_f_walk1',
  'mario_f_walk2',
  'mario_f_walk3',
  'mario_f_jump',
  'goomba_0',
  'goomba_walk2',
  'goomba_flat',
  'koopa_0',
  'koopa_1',
  'koopa_shell',
  'bowser',
  'mushroom',
  'fireflower',
  'coin_0',
  'coin_spin1',
  'coin_spin2',
  'coin_spin3',
  'coin_spin4',
  'axe',
  'fireball',
  'fireball_1',
  'flagpole',
  'flag',
  'block_ground',
  'block_brick',
  'qblock_1',
  'qblock_2',
  'qblock_3',
  'qblock_empty',
  'castle',
  'pipe',
  'pipe_top',
  'pipe_body',
  'tiles',
  'bush',
  'cloud',
  'hill',
] as const;

export type SheetTextureKey = (typeof SHEET_TEXTURE_KEYS)[number];
